### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by SolitudeSF** [ABuffSeagull/kakoune-discord#1]
`discord.kak` uses bashisms, that prevent it working with `sh`. Fixing them hangs kakoune.

**Comment by ABuffSeagull** [comment]
As I am *not* very well versed with the differences between all the shells, which exactly is the bash specific part?
And for that matter, why would it work fine on my computer :thinking:. I guess my `sh` is aliased to `bash`.

**Comment by SolitudeSF** [comment]
`[[` is bashism, but changing it to posix `[` doesnt make the plugin work.

**Comment by ABuffSeagull** [comment]
hmmmmmmmm :thinking: changing double bracket to single still works for me.
What's your `sh --version`?
And can't think of why it would be hanging, except maybe it's getting blocked on writing to the fifo, but that would mean the rust program isn't running.

**Comment by SolitudeSF** [comment]
`dash` doesnt have version flag. its latest anyway.
`kakoune-discord` is daemonized and running. but kakoune cant start.

**Comment by ABuffSeagull** [comment]
Okay, I think I got it.
I was able to reproduce the problem, and apparently it's again cause I don't understand shells :laughing: 
I saw in the [docs](https://github.com/mawww/kakoune/blob/551021d6e5360c48c0d08da6464a2ee4081bb3d8/doc/interfacing.asciidoc#basic-interaction) to use
```sh
{ command } > /dev/null 2>&1 < /dev/null &
```
and I thought I could be cheeky and shorten it to:
```sh
{ command } &> /dev/null < /dev/null &
```
but apparently that blocks on `dash`. Changing it back to the original unblocks it.
If you could confirm this works, I'll push the changes.

**Comment by ABuffSeagull** [comment]
Eh, I'll just push it anyway. Thanks for introducing dash to me, I'm gonna be trying it out more in Kakoune.

**Comment by SolitudeSF** [comment]
yep, that works.
